name: NuGet package

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test 
      
   # - name: Packing
     # run: dotnet pack  -c Release 
      
    - name: Publish GitHub
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate --source https://nuget.pkg.github.com/Platonenkov/index.json -k ${{secrets.GITHUB_TOKEN}}       
    # опубликовать пакет в личном репозитории NuGet   
    - name: Publish Nuget
      run: dotnet nuget push "**/*.nupkg" -k ${{secrets.NuGetApiKey}} --skip-duplicate -s https://api.nuget.org/v3/index.json
